[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://piratabackend.onrender.com/api"
  CI = "false"
  NODE_VERSION = "18.17.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
