services:
  - type: web
    name: pirata-tecnologico
    env: static
    buildCommand: npm ci && CI=false npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://piratabackend.onrender.com/api
      - key: CI
        value: "false"
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
